export type UniversityImage = {
  src: string;
  alt: string;
  credit?: string;
  objectPosition?: string;
};

export const universityImages: Record<string, UniversityImage> = {
  keio: {
    src: "/images/universities/keio.webp",
    alt: "慶應義塾大学信濃町キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  jikei: {
    src: "/images/universities/jikei.webp",
    alt: "東京慈恵会医科大学本院",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  juntendo: {
    src: "/images/universities/juntendo.webp",
    alt: "順天堂大学本郷キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  showa: {
    src: "/images/universities/showa.webp",
    alt: "昭和医科大学旗の台キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  nihon: {
    src: "/images/universities/nihon.webp",
    alt: "日本大学医学部板橋キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "nippon-medical": {
    src: "/images/universities/nippon-medical.webp",
    alt: "日本医科大学千駄木キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  toho: {
    src: "/images/universities/toho.webp",
    alt: "東邦大学大森キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  kyorin: {
    src: "/images/universities/kyorin.webp",
    alt: "杏林大学三鷹キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  kitasato: {
    src: "/images/universities/kitasato.webp",
    alt: "北里大学相模原キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  tokai: {
    src: "/images/universities/tokai.webp",
    alt: "東海大学伊勢原キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  kindai: {
    src: "/images/universities/kindai.webp",
    alt: "近畿大学医学部キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "osaka-ika": {
    src: "/images/universities/osaka-ika.webp",
    alt: "大阪医科薬科大学本部キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "kansai-ika": {
    src: "/images/universities/kansai-ika.webp",
    alt: "関西医科大学枚方キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  fukuoka: {
    src: "/images/universities/fukuoka.webp",
    alt: "福岡大学医学部七隈キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  teikyo: {
    src: "/images/universities/teikyo.webp",
    alt: "帝京大学板橋キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "tohoku-ika": {
    src: "/images/universities/tohoku-ika.webp",
    alt: "東北医科薬科大学小松島キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  fujita: {
    src: "/images/universities/fujita.webp",
    alt: "藤田医科大学豊明キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "aichi-ika": {
    src: "/images/universities/aichi-ika.webp",
    alt: "愛知医科大学長久手キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  hyogo: {
    src: "/images/universities/hyogo.webp",
    alt: "兵庫医科大学西宮キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "kawasaki-ika": {
    src: "/images/universities/kawasaki-ika.webp",
    alt: "川崎医科大学倉敷キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  kurume: {
    src: "/images/universities/kurume.webp",
    alt: "久留米大学医学部旭町キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  iwate: {
    src: "/images/universities/iwate.webp",
    alt: "岩手医科大学矢巾キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  dokkyo: {
    src: "/images/universities/dokkyo.webp",
    alt: "獨協医科大学壬生キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "joshi-ika": {
    src: "/images/universities/joshi-ika.webp",
    alt: "東京女子医科大学河田町キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "kanazawa-ika": {
    src: "/images/universities/kanazawa-ika.webp",
    alt: "金沢医科大学内灘キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  iuhw: {
    src: "/images/universities/iuhw.webp",
    alt: "国際医療福祉大学成田キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "saitama-ika": {
    src: "/images/universities/saitama-ika.webp",
    alt: "埼玉医科大学毛呂山キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  marianna: {
    src: "/images/universities/marianna.webp",
    alt: "聖マリアンナ医科大学宮前キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  "tokyo-ika": {
    src: "/images/universities/tokyo-ika.webp",
    alt: "東京医科大学新宿キャンパス",
    credit: "Photo: Wikimedia Commons",
    objectPosition: "center",
  },
  // ── 国公立・防衛医大 ──
  hokkaido: { src: "/images/universities/hokkaido.webp", alt: "北海道大学札幌キャンパス", credit: "Photo: Wikimedia Commons" },
  "asahikawa-medical": { src: "/images/universities/asahikawa-medical.webp", alt: "旭川医科大学キャンパス", credit: "Photo: Wikimedia Commons" },
  hirosaki: { src: "/images/universities/hirosaki.webp", alt: "弘前大学キャンパス", credit: "Photo: Wikimedia Commons" },
  tohoku: { src: "/images/universities/tohoku.webp", alt: "東北大学病院", credit: "Photo: Wikimedia Commons" },
  akita: { src: "/images/universities/akita.webp", alt: "秋田大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  yamagata: { src: "/images/universities/yamagata.webp", alt: "山形大学医学部", credit: "Photo: Wikimedia Commons" },
  "fukushima-medical": { src: "/images/universities/fukushima-medical.webp", alt: "福島県立医科大学", credit: "Photo: Wikimedia Commons" },
  tsukuba: { src: "/images/universities/tsukuba.webp", alt: "筑波大学附属病院", credit: "Photo: Wikimedia Commons" },
  gunma: { src: "/images/universities/gunma.webp", alt: "群馬大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  chiba: { src: "/images/universities/chiba.webp", alt: "千葉大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  tokyo: { src: "/images/universities/tokyo.webp", alt: "東京大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  "tokyo-science": { src: "/images/universities/tokyo-science.webp", alt: "東京科学大学湯島キャンパス", credit: "Photo: Wikimedia Commons" },
  niigata: { src: "/images/universities/niigata.webp", alt: "新潟大学医歯学総合病院", credit: "Photo: Wikimedia Commons" },
  toyama: { src: "/images/universities/toyama.webp", alt: "富山大学附属病院", credit: "Photo: Wikimedia Commons" },
  kanazawa: { src: "/images/universities/kanazawa.webp", alt: "金沢大学附属病院", credit: "Photo: Wikimedia Commons" },
  fukui: { src: "/images/universities/fukui.webp", alt: "福井大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  yamanashi: { src: "/images/universities/yamanashi.webp", alt: "山梨大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  shinshu: { src: "/images/universities/shinshu.webp", alt: "信州大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  gifu: { src: "/images/universities/gifu.webp", alt: "岐阜大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  "hamamatsu-medical": { src: "/images/universities/hamamatsu-medical.webp", alt: "浜松医科大学キャンパス", credit: "Photo: Wikimedia Commons" },
  nagoya: { src: "/images/universities/nagoya.webp", alt: "名古屋大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  mie: { src: "/images/universities/mie.webp", alt: "三重大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  "shiga-medical": { src: "/images/universities/shiga-medical.webp", alt: "滋賀医科大学キャンパス", credit: "Photo: Wikimedia Commons" },
  kyoto: { src: "/images/universities/kyoto.webp", alt: "京都大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  osaka: { src: "/images/universities/osaka.webp", alt: "大阪大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  kobe: { src: "/images/universities/kobe.webp", alt: "神戸大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  tottori: { src: "/images/universities/tottori.webp", alt: "鳥取大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  shimane: { src: "/images/universities/shimane.webp", alt: "島根大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  okayama: { src: "/images/universities/okayama.webp", alt: "岡山大学病院", credit: "Photo: Wikimedia Commons" },
  hiroshima: { src: "/images/universities/hiroshima.webp", alt: "広島大学病院", credit: "Photo: Wikimedia Commons" },
  yamaguchi: { src: "/images/universities/yamaguchi.webp", alt: "山口大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  tokushima: { src: "/images/universities/tokushima.webp", alt: "徳島大学病院", credit: "Photo: Wikimedia Commons" },
  kagawa: { src: "/images/universities/kagawa.webp", alt: "香川大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  ehime: { src: "/images/universities/ehime.webp", alt: "愛媛大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  kochi: { src: "/images/universities/kochi.webp", alt: "高知大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  kyushu: { src: "/images/universities/kyushu.webp", alt: "九州大学病院", credit: "Photo: Wikimedia Commons" },
  saga: { src: "/images/universities/saga.webp", alt: "佐賀大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  nagasaki: { src: "/images/universities/nagasaki.webp", alt: "長崎大学病院", credit: "Photo: Wikimedia Commons" },
  kumamoto: { src: "/images/universities/kumamoto.webp", alt: "熊本大学病院", credit: "Photo: Wikimedia Commons" },
  oita: { src: "/images/universities/oita.webp", alt: "大分大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  miyazaki: { src: "/images/universities/miyazaki.webp", alt: "宮崎大学医学部附属病院", credit: "Photo: Wikimedia Commons" },
  kagoshima: { src: "/images/universities/kagoshima.webp", alt: "鹿児島大学キャンパス", credit: "Photo: Wikimedia Commons" },
  ryukyu: { src: "/images/universities/ryukyu.webp", alt: "琉球大学西普天間キャンパス", credit: "Photo: Wikimedia Commons" },
  ndmc: { src: "/images/universities/ndmc.webp", alt: "防衛医科大学校所沢キャンパス", credit: "Photo: Wikimedia Commons" },
};

export function getUniversityImage(slug: string): UniversityImage | null {
  return universityImages[slug] ?? null;
}
